### ISSUE TITLE
Incorrect mesh for Spirit Blossom Kindred

### ISSUE THREAD

**Issue by l30ch** [BilbozZ/lolblender#4]
![image](https://user-images.githubusercontent.com/70063047/90956889-04e09380-e4bd-11ea-9cd8-b64456b01864.png)

The add-on works like a charm on other skins but it's causing troubles exclusively on the spirit blossom kindred skin. The mesh gets all messed up everytime I try to convert it. However, the skeleton seems to be looking normal. 

I extracted the files using obsidian, and I'm not sure whether this is a problem with this add-on or obsidian itself. Does anyone have an idea to fixing this?

**Comment by BilbozZ** [comment]
I am not able to reproduce your results with the newest version of Obsidian (Version 4.1) and the newest version of lolblender.

**Comment by l30ch** [comment]
Thanks for the reply! I was able to import the file correctly after reinstalling the add-on. Think it was a mistake on my part. Sorry for the trouble.
